/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetablesRouteImport } from './routes/timetables'
import { Route as StopsRouteImport } from './routes/stops'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as RouteBuilderRouteImport } from './routes/route-builder'
import { Route as LiveMapRouteImport } from './routes/live-map'
import { Route as DataRouteImport } from './routes/data'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutesIndexRouteImport } from './routes/routes.index'
import { Route as RoutesNewRouteImport } from './routes/routes.new'
import { Route as RoutesRouteIdRouteImport } from './routes/routes.$routeId'

const TimetablesRoute = TimetablesRouteImport.update({
  id: '/timetables',
  path: '/timetables',
  getParentRoute: () => rootRouteImport,
} as any)
const StopsRoute = StopsRouteImport.update({
  id: '/stops',
  path: '/stops',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteBuilderRoute = RouteBuilderRouteImport.update({
  id: '/route-builder',
  path: '/route-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMapRoute = LiveMapRouteImport.update({
  id: '/live-map',
  path: '/live-map',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoutesRoute,
} as any)
const RoutesNewRoute = RoutesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RoutesRoute,
} as any)
const RoutesRouteIdRoute = RoutesRouteIdRouteImport.update({
  id: '/$routeId',
  path: '/$routeId',
  getParentRoute: () => RoutesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/live-map': typeof LiveMapRoute
  '/route-builder': typeof RouteBuilderRoute
  '/routes': typeof RoutesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/stops': typeof StopsRoute
  '/timetables': typeof TimetablesRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/routes/new': typeof RoutesNewRoute
  '/routes/': typeof RoutesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/live-map': typeof LiveMapRoute
  '/route-builder': typeof RouteBuilderRoute
  '/settings': typeof SettingsRoute
  '/stops': typeof StopsRoute
  '/timetables': typeof TimetablesRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/routes/new': typeof RoutesNewRoute
  '/routes': typeof RoutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/live-map': typeof LiveMapRoute
  '/route-builder': typeof RouteBuilderRoute
  '/routes': typeof RoutesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/stops': typeof StopsRoute
  '/timetables': typeof TimetablesRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/routes/new': typeof RoutesNewRoute
  '/routes/': typeof RoutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data'
    | '/live-map'
    | '/route-builder'
    | '/routes'
    | '/settings'
    | '/stops'
    | '/timetables'
    | '/routes/$routeId'
    | '/routes/new'
    | '/routes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data'
    | '/live-map'
    | '/route-builder'
    | '/settings'
    | '/stops'
    | '/timetables'
    | '/routes/$routeId'
    | '/routes/new'
    | '/routes'
  id:
    | '__root__'
    | '/'
    | '/data'
    | '/live-map'
    | '/route-builder'
    | '/routes'
    | '/settings'
    | '/stops'
    | '/timetables'
    | '/routes/$routeId'
    | '/routes/new'
    | '/routes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRoute: typeof DataRoute
  LiveMapRoute: typeof LiveMapRoute
  RouteBuilderRoute: typeof RouteBuilderRoute
  RoutesRoute: typeof RoutesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  StopsRoute: typeof StopsRoute
  TimetablesRoute: typeof TimetablesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetables': {
      id: '/timetables'
      path: '/timetables'
      fullPath: '/timetables'
      preLoaderRoute: typeof TimetablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stops': {
      id: '/stops'
      path: '/stops'
      fullPath: '/stops'
      preLoaderRoute: typeof StopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-builder': {
      id: '/route-builder'
      path: '/route-builder'
      fullPath: '/route-builder'
      preLoaderRoute: typeof RouteBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-map': {
      id: '/live-map'
      path: '/live-map'
      fullPath: '/live-map'
      preLoaderRoute: typeof LiveMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof RoutesRoute
    }
    '/routes/new': {
      id: '/routes/new'
      path: '/new'
      fullPath: '/routes/new'
      preLoaderRoute: typeof RoutesNewRouteImport
      parentRoute: typeof RoutesRoute
    }
    '/routes/$routeId': {
      id: '/routes/$routeId'
      path: '/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof RoutesRouteIdRouteImport
      parentRoute: typeof RoutesRoute
    }
  }
}

interface RoutesRouteChildren {
  RoutesRouteIdRoute: typeof RoutesRouteIdRoute
  RoutesNewRoute: typeof RoutesNewRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
}

const RoutesRouteChildren: RoutesRouteChildren = {
  RoutesRouteIdRoute: RoutesRouteIdRoute,
  RoutesNewRoute: RoutesNewRoute,
  RoutesIndexRoute: RoutesIndexRoute,
}

const RoutesRouteWithChildren =
  RoutesRoute._addFileChildren(RoutesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRoute: DataRoute,
  LiveMapRoute: LiveMapRoute,
  RouteBuilderRoute: RouteBuilderRoute,
  RoutesRoute: RoutesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  StopsRoute: StopsRoute,
  TimetablesRoute: TimetablesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
